### ISSUE TITLE
Azure configuration for multiple deployments

### ISSUE THREAD

**Issue by Yanick-Salzmann** [quarkiverse/quarkus-langchain4j#237]
In my opinion there is an issue with the configuration for Azure. At the moment the following config options are possible (some more are there but relevant to my question here):
```yaml
quarkus.langchain4j.azure-openai:
    - resourceName
    - deploymentId
    - baseUrl

    - embeddingModel:
       - ...
    
    - chatModel:
       - ...  
```

The deploymentId will identify the model in Azure. With the configuration currently I am not able to configure a different model for embeddings and for chat, however my situation is the following, that under the resource name `my-company-playground-use` I have two deployments, one is `chat-completion` which is a gpt4 model and one is `embedding-model` which is an ada-002 model. I want to use the `chat-completion` deployment for the `chatModel` above and the deployment `embedding-model` for the `embeddingModel` above. This is not currently possible. I would need to have the possibility to configure:

```properties
quarkus.langchain4j.azure-openai.resourceName=mycompany-playground-use
quarkus.langchain4j.azure-openai.embedding-model.deploymentId=embedding-model
quarkus.langchain4j.azure-openai.chat-model.deploymentId=chat-model
```

I am willing to work on this, however I was wondering what your opinions are and/or if you have already had some considerations regarding that.
