### ISSUE TITLE
How to enable JSON mode for azure-openai ?

### ISSUE THREAD

**Issue by Plawn** [quarkiverse/quarkus-langchain4j#466]
Hello, 

Sorry to bother you with such questions :), 

I can't seem to enable the json mode with azure-open, looking in the code, it seems it should work with this configuration but It's not working.

```yaml
quarkus:
  # settings for the models
  langchain4j:
    azure-openai: # should be azure open ai
      api-key:<key>
      resource-name: <name>
      deployment-name: <name>
      response-format: json_object
```

Looking in the langchain4j documentation, It looks like the way to configure the `responseFormat` is not the Same for the OpenAIClient and the AzureOpenAiClient.

Thanks
